### ISSUE TITLE
pyGTK?

### ISSUE THREAD

**Issue by jswoboda** [ryanvolz/conda-recipes#1]
Do you need pyGTK to run gnuradio on ubuntu? On macOS its a requirement to run gunradio companion.

**Comment by ryanvolz** [comment]
You do, but last I knew it wasn't packaged for conda-forge and I didn't have the patience to make one. What I did for my Linux build was just not provide pyGTK, which causes gnuradio companion to be disabled and not built by default.

**Comment by jswoboda** [comment]
Alright so I could see if the recipe works with what you have just not with the pyGTK. I was worried that without companion dgital_rf wouldn't build.

**Comment by ryanvolz** [comment]
digital_rf will build, thor will work fine, you just won't be able to use gnuradio companion to make or edit flowgraphs (from within the conda environment, you could still use an external grc to do that and then run the flowgraph manually with the generated python script in the conda environment).
